### ISSUE TITLE
Time shift at day change

### ISSUE THREAD

**Issue by blaumeik51** [FL550/simple_dwd_weatherforecast#3]
Hello, I noticed a reproducable one day shift of th e data at 0:00 o'clock. The shift exists also at 0:30 but disapears at 1:00 o'clock. I am using the dwdforecast.Weather method. Basically at 0:00 o'clock the data contains only 9 days.

Regards

Meik

**Comment by blaumeik51** [comment]
Maybe to get more precise. At 0:00 o'clock, the data shift one day in a way that the data from the just started day disapear and the prediction contains only 9 days. The time stamps stay the same, so just the values shift and the data set is not extended with day ten.

**Comment by FL550** [comment]
Thanks for the bug report. I will check the reason for this. Maybe it's time to write unittests.

**Comment by FL550** [comment]
You are accessing the forecast dict directly, right? And not using any of the methods to access the underlying data?

**Comment by blaumeik51** [comment]
Yes correct.

**Comment by FL550** [comment]
I released v1.0.7 which should hopefully address this issue.

**Comment by blaumeik51** [comment]
Hey. Unfortunately the problem still exists. Its just hour 0 in local time that has the issue. Before winter time the problem was not existent. It just apeared with shifting to winter time. Maybe that helps.

**Comment by FL550** [comment]
I need more info to track this bug. Are you calling the update method directly prior to accessing the data?

**Comment by blaumeik51** [comment]
Hey. Yes, one line before. 
dwd_weather = dwdforecast.Weather(str(weatherStation.id[0]))  # Flughafen Hamburg
                dwd_weather.update()
weatherData = pd.DataFrame(dwd_weather.forecast_data).T.reset_index()

**Comment by FL550** [comment]
I haven't forgotten your issue, but it's not easy to debug. From reviewing the code, I wasn't able to identify the reason for the shift of the data.

**Comment by blaumeik51** [comment]
Let me know if I can help.

**Comment by FL550** [comment]
Thanks! I am logging the data now for the next days to see if I can find the issue.

**Comment by FL550** [comment]
I can't reproduce this on my machine. I logged the content of the `forecast_data` dict every half hour and everything works as expected and no shift of the data occurs. Can you maybe investigate a bit on your side as I have no idea how this can happen to you?

**Comment by blaumeik51** [comment]
Hey. Yes I will try my best an let you know.

**Comment by FL550** [comment]
Thank you very much!

**Comment by FL550** [comment]
Do you have any news on this?

**Comment by FL550** [comment]
I'll close this for now, as I can't reproduce the behavior you reported. Feel free to reopen if you encounter this issue again.
